name: test

on:
  - push

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: allenevans/set-env@v1.0.0
        with:
          SNOOP_VERSION: '2'

      - run: julia -e "using Pkg; Pkg.add(PackageSpec(\"SnoopCompile\", version = \"${SNOOP_VERSION}\"))"

  test2:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - run: julia -e "using Pkg; Pkg.add(PackageSpec(\"SnoopCompile\", version = \"${SNOOP_VERSION}\"))"
