name: test

on:
  - push

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - run: julia -e 'using Pkg; Pkg.add(PackageSpec(name="SnoopCompile", version = "2"))'
